"use client";

import { CheckCircle, HourglassMedium, ShieldWarning } from "@phosphor-icons/react";
import Link from "next/link";

import type { ReconciliationRun } from "@/features/accounts/types";
import { CopyControl, DataTableRegion, PageHeader, Pagination, RecordLink, StatePanel, StatusBadge } from "@/features/console/components";
import { utcDateTime } from "@/features/console/format";
import { ReconciliationCommand } from "@/features/reconciliation/ReconciliationCommand";

function runTone(status: ReconciliationRun["status"]) { return status === "matched" ? "success" as const : status === "mismatch" || status === "failed" ? "danger" as const : "warning" as const; }
function runLabel(status: ReconciliationRun["status"]) { return status === "matched" ? "Passed" : status === "mismatch" ? "Mismatch detected" : status === "failed" ? "Failed" : "Running"; }

function RunEvidence({ run }: Readonly<{ run: ReconciliationRun }>) {
  const running=run.status==="running";
  const passed=run.status==="matched"&&run.mismatch_count==="0"&&Boolean(run.ledger_watermark)&&Boolean(run.completed_at);
  return <><section className={`evidence-hero ${passed?"":"unavailable"}`}>{passed?<CheckCircle weight="fill" aria-hidden="true"/>:running?<HourglassMedium weight="fill" aria-hidden="true"/>:<ShieldWarning weight="fill" aria-hidden="true"/>}<div><p className="eyebrow">{running?"Authoritative run in progress":"Authoritative completed run"}</p><h2>{runLabel(run.status)}</h2><p>{running?"No pass or mismatch result is inferred while this run is active.":`${run.checked_account_count} accounts · ${run.posting_count} postings · ${run.mismatch_count} mismatches`}</p></div><StatusBadge tone={runTone(run.status)}>{runLabel(run.status)}</StatusBadge></section><section className="identity-strip"><div><span>Run ID</span><CopyControl value={run.run_id}/></div><div><span>Scope</span><strong>{run.scope||"Recorded tenant scope"}</strong></div><div><span>Ledger watermark</span><strong>{run.ledger_watermark||"Pending authoritative capture"}</strong></div><div><span>{running?"Started":"Completed"}</span><strong>{utcDateTime(running?run.started_at:run.completed_at)}</strong></div></section>{run.mismatch_count!=="0"&&<StatePanel kind="error" title={`${run.mismatch_count} mismatch${run.mismatch_count==="1"?"":"es"} require investigation`} message="This financial control did not pass. A mismatch cannot be marked resolved in the console; only a new authoritative run can establish later evidence."/>}{run.mismatches&&run.mismatches.length>0&&<section className="ledger-section reconciliation-mismatches" aria-labelledby="reconciliation-mismatches-heading"><div className="section-heading"><div><p className="eyebrow">Stop-ship evidence</p><h3 id="reconciliation-mismatches-heading">Affected records</h3><p>Open only tenant-authorized account evidence. Exact mismatch values remain tied to this immutable run.</p></div></div><DataTableRegion label="Reconciliation mismatch evidence"><table className="data-table"><thead><tr><th>Mismatch ID</th><th>Classification</th><th>Account evidence</th><th>Expected / observed</th><th>Balance version</th></tr></thead><tbody>{run.mismatches.map((mismatch)=><tr key={mismatch.mismatch_id}><td><CopyControl value={mismatch.mismatch_id}/></td><td>{mismatch.classification}</td><td>{mismatch.account_id?<RecordLink href={`/accounts/${encodeURIComponent(mismatch.account_id)}`} label="Open affected account" id={`mismatch-account-${mismatch.mismatch_id}`}/>:"No account record supplied"}</td><td className="number-cell">{mismatch.currency||"INR"} {mismatch.expected_minor??"Unavailable"} / {mismatch.observed_minor??mismatch.observed_available_minor??"Unavailable"}</td><td><code>{mismatch.balance_version??"Unavailable"}</code></td></tr>)}</tbody></table></DataTableRegion></section>}</>;
}

export function ReconciliationView({ runs, detail, detailRequested, error, loading, nextCursor, tenantId, csrfToken, online, canWrite, onObserved, onRefresh, onMore }: Readonly<{ runs: ReconciliationRun[]; detail: ReconciliationRun|null;detailRequested:boolean;error:string|null;loading:boolean;nextCursor?:string;tenantId:string;csrfToken:string;online:boolean;canWrite:boolean;onObserved:(run:ReconciliationRun)=>void;onRefresh:()=>Promise<void>;onMore:()=>void }>) {
  if(detail)return <><PageHeader eyebrow="Control evidence / Immutable run" title="Reconciliation detail" description="Evidence returned by the tenant-authorized PostgreSQL control record."/><RunEvidence run={detail}/><section className="surface detail-document"><dl className="evidence-list"><div><dt>Correlation ID</dt><dd><CopyControl value={detail.correlation_id}/></dd></div><div><dt>Application version</dt><dd>{detail.application_version||"Unavailable"}</dd></div><div><dt>Started</dt><dd>{utcDateTime(detail.started_at)}</dd></div><div><dt>Completed</dt><dd>{utcDateTime(detail.completed_at)}</dd></div></dl></section><Link className="text-link back-link" href="/reconciliation">← Back to reconciliation history</Link></>;
  if(detailRequested)return <><PageHeader eyebrow="Control evidence / Immutable run" title="Reconciliation detail" description="Loading the requested tenant-authorized control record."/>{error?<StatePanel kind="error" title="Evidence unavailable" message={error}/>:<StatePanel title="Loading reconciliation evidence" message="No passing or mismatch result is inferred while the authoritative run is loading."/>}</>;
  const latest=runs[0];return <><PageHeader eyebrow="Control evidence / Authoritative ledger" title="Reconciliation" description="Verify whether projected account balances agree with immutable double-entry postings."><button className="button secondary" type="button" disabled={loading||!online} onClick={()=>void onRefresh()}>Refresh evidence</button></PageHeader><ReconciliationCommand tenantId={tenantId} csrfToken={csrfToken} online={online} canWrite={canWrite} latestRun={latest??null} onObserved={onObserved} onRefreshHistory={onRefresh}/>{error?<StatePanel kind="error" title="Evidence unavailable" message={error}/>:loading&&!latest?<StatePanel title="Loading reconciliation evidence" message="No result is inferred until an authoritative run has been returned."/>:!latest?<StatePanel kind="unknown" title="No reconciliation evidence" message="LedgerSync cannot claim a passing result until an authoritative completed run exists."/>:<RunEvidence run={latest}/>} {runs.length>0&&<section className="ledger-section"><div className="section-heading"><div><p className="eyebrow">Immutable history</p><h2>Reconciliation runs</h2><p>Each result retains its scope, counts, watermark, and completion time. Starting a new run never replaces prior evidence.</p></div></div><DataTableRegion label="Reconciliation run history"><table className="data-table"><thead><tr><th>Run ID</th><th>Result</th><th>Scope</th><th>Accounts / postings</th><th>Mismatches</th><th>Completed UTC</th><th>Action</th></tr></thead><tbody>{runs.map((run)=><tr key={run.run_id}><td><CopyControl value={run.run_id}/></td><td><StatusBadge tone={runTone(run.status)}>{runLabel(run.status)}</StatusBadge></td><td>{run.scope}</td><td>{run.checked_account_count} / {run.posting_count}</td><td className="number-cell">{run.mismatch_count}</td><td>{run.status==="running"?"In progress":utcDateTime(run.completed_at)}</td><td><RecordLink href={`/reconciliation/${run.run_id}`} label="Open evidence"/></td></tr>)}</tbody></table></DataTableRegion><Pagination nextCursor={nextCursor} busy={loading} onNext={onMore}/></section>}</>;
}
