"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

import { BalanceStatus } from "@/features/accounts/BalanceStatus";
import { TransactionLedger } from "@/features/accounts/TransactionLedger";
import type { Account, Transaction } from "@/features/accounts/types";
import { CopyControl, PageHeader, RecordLink, StatePanel, StatusBadge } from "@/features/console/components";
import { accountLabel, utcDateTime } from "@/features/console/format";
import { formatMinorUnits } from "@/lib/money";

function tone(status: Account["status"]) { return status === "active" ? "success" : status === "frozen" ? "warning" : "neutral"; }

export function AccountsView({ accounts, selected, balance, transactions, balanceLoading, historyLoading, balanceError, historyError, error, online, onRefresh }: Readonly<{ accounts: Account[]; selected: Account | null; balance: Account | null; transactions: Transaction[]; balanceLoading: boolean; historyLoading: boolean; balanceError: string | null; historyError: string | null; error: string | null; online: boolean; onRefresh: () => void }>) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all");
  const filtered = useMemo(() => accounts.filter((account) => (status === "all" || account.status === status) && `${account.display_name} ${account.account_id} ${account.external_reference}`.toLowerCase().includes(query.toLowerCase())), [accounts, query, status]);
  return <><PageHeader eyebrow="Ledger / Account directory" title={selected ? accountLabel(selected) : "Accounts"} description={selected ? "Authoritative balance, account identity, and immutable posting history." : "Search only the accounts authorized for this operator."}><button className="button secondary" type="button" onClick={onRefresh} disabled={!online}>Refresh evidence</button></PageHeader>
    {error && <StatePanel kind="error" title="Accounts unavailable" message={error} />}
    {!selected && !error && <><div className="filter-bar"><label>Search accounts<input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, ID, or reference" /></label><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="frozen">Frozen</option><option value="closed">Closed</option></select></label><span>{filtered.length} result{filtered.length === 1 ? "" : "s"}</span></div>
      {filtered.length === 0 ? <StatePanel title="No matching accounts" message="Clear or change the filters. LedgerSync does not broaden the authorized account scope." /> : <section className="ledger-section account-directory" aria-labelledby="accounts-heading"><div className="section-heading"><div><p className="eyebrow">Authorized scope</p><h2 id="accounts-heading">Available balances</h2></div></div><div className="data-table-wrap" role="region" aria-label="Authorized account comparison" tabIndex={0}><table className="data-table"><thead><tr><th>Account</th><th>Category</th><th>Status</th><th>Available balance</th><th>Version / as of</th><th>Action</th></tr></thead><tbody>{filtered.map((account) => <tr key={account.account_id}><td><strong>{accountLabel(account)}</strong><code>{account.account_id}</code></td><td>{account.category?.replaceAll("_", " ") ?? "Unclassified"}</td><td><StatusBadge tone={tone(account.status)}>{account.status}</StatusBadge></td><td className="number-cell">{formatMinorUnits(account.currency, account.available_minor)}</td><td><code>v{account.version}</code><small>{utcDateTime(account.as_of)}</small></td><td><RecordLink href={`/accounts/${account.account_id}`} label="Open account" /></td></tr>)}</tbody></table></div><div className="record-card-list">{filtered.map((account) => <article className="record-card" key={account.account_id}><div><StatusBadge tone={tone(account.status)}>{account.status}</StatusBadge><span>{account.category?.replaceAll("_", " ")}</span></div><h3>{accountLabel(account)}</h3><strong>{formatMinorUnits(account.currency, account.available_minor)}</strong><CopyControl value={account.account_id} label={`Copy ${accountLabel(account)} ID`} /><small>Version {account.version} · {utcDateTime(account.as_of)}</small><RecordLink href={`/accounts/${account.account_id}`} label="Open account" /></article>)}</div></section>}</>}
    {selected && <><section className="identity-strip"><div><span>Account ID</span><CopyControl value={selected.account_id} /></div><div><span>External reference</span><strong>{selected.external_reference || "Not set"}</strong></div><div><span>Category</span><strong>{selected.category?.replaceAll("_", " ") || "Unclassified"}</strong></div><div><span>Status</span><StatusBadge tone={tone(selected.status)}>{selected.status}</StatusBadge></div></section>{selected.status === "frozen" && <StatePanel kind="unknown" title="Account is frozen" message="The balance remains visible, but this account cannot be selected for a new debit or credit." />}<div className="account-detail-grid"><BalanceStatus currency={balance?.currency ?? selected.currency} availableMinor={balance?.available_minor} version={balance?.version} asOf={balance?.as_of} loading={balanceLoading} error={balanceError} /><TransactionLedger transactions={transactions} account={selected} loading={historyLoading} error={historyError} /></div><Link className="text-link back-link" href="/accounts">← Back to account directory</Link></>}
  </>;
}
