"use client";

import { HardDrives, ShieldWarning } from "@phosphor-icons/react";
import Link from "next/link";

import { CopyControl, PageHeader, StatePanel, StatusBadge } from "@/features/console/components";
import { utcDateTime } from "@/features/console/format";
import type { LocalDiagnostics } from "@/lib/api/operations";
import type { RecoveryEvidenceIndex } from "@/lib/api/recovery";

const commands=[
  {label:"Create protected backup",value:".\\scripts\\backup-local.ps1",detail:"Streams a finalized host-side backup. The browser never receives its content or path."},
  {label:"Run isolated restore drill",value:".\\scripts\\local-restore-drill.ps1",detail:"Restores into an isolated environment and validates reconciliation without replacing the active database."},
  {label:"Inspect local status",value:".\\scripts\\status-local.ps1",detail:"Reads the bounded local status report without granting this page shell access."},
] as const;

function count(value:number){return Number.isSafeInteger(value)?value.toLocaleString("en-IN"):"Not available";}

export function RecoveryView({diagnostics,recovery,diagnosticsError,recoveryError,loading,online,canRead,canReadDiagnostics,onRefresh}:Readonly<{diagnostics:LocalDiagnostics|null;recovery:RecoveryEvidenceIndex|null;diagnosticsError:string|null;recoveryError:string|null;loading:boolean;online:boolean;canRead:boolean;canReadDiagnostics:boolean;onRefresh:()=>void;}>) {
  const backup=recovery?.latest_backup; const restore=recovery?.latest_restore;
  return <>
    <PageHeader eyebrow="Local tools / Protected recovery" title="Recovery Center" description="Verify the recovery custody chain, then copy a reviewed host command when new evidence is required."><button className="button secondary" type="button" disabled={!online||loading||!canRead} onClick={onRefresh}>{loading?"Refreshing…":"Refresh evidence"}</button></PageHeader>
    {!canRead&&<StatePanel kind="denied" title="Recovery evidence not authorized" message="This operator session does not include recovery:read. No backup or restore evidence is disclosed."/>}
    {canRead&&loading&&!diagnostics&&!recovery&&<StatePanel title="Loading recovery evidence" message="Current PostgreSQL truth and protected host evidence are loading through separate read boundaries."/>}
    {canRead&&<section className="recovery-chain" aria-labelledby="recovery-chain-heading" aria-busy={loading}><div className="section-heading"><div><p className="eyebrow">Three independent proofs</p><h2 id="recovery-chain-heading">Recovery custody chain</h2><p>A healthy database, a valid backup, and a passing isolated restore answer different questions. No step substitutes for another.</p></div></div>
      <ol>
        <li className={!diagnostics||diagnostics.financial_authority.postgres.state!=="reachable"?"unavailable":"verified"}><span className="recovery-chain-marker">01</span><div><p className="eyebrow">Current financial authority</p><h3>PostgreSQL now</h3>{!canReadDiagnostics?<StatePanel kind="denied" title="Current database scope not authorized" message="local:read is required to inspect the current PostgreSQL and reconciliation state."/>:diagnosticsError?<StatePanel kind="error" title="Current database evidence unavailable" message={diagnosticsError}/>:diagnostics?<><StatusBadge tone={diagnostics.financial_authority.postgres.state==="reachable"?"success":"danger"}>{diagnostics.financial_authority.postgres.state==="reachable"?"Reachable":"Unavailable"}</StatusBadge><dl><div><dt>Schema version</dt><dd><code>{diagnostics.financial_authority.postgres.schema_version??"Not available"}</code></dd></div><div><dt>Latest reconciliation</dt><dd>{diagnostics.financial_authority.latest_reconciliation.state==="available"?<><StatusBadge tone={diagnostics.financial_authority.latest_reconciliation.status==="matched"?"success":"danger"}>{diagnostics.financial_authority.latest_reconciliation.status??"Unknown"}</StatusBadge>{diagnostics.financial_authority.latest_reconciliation.run_id&&<Link href={`/reconciliation/${encodeURIComponent(diagnostics.financial_authority.latest_reconciliation.run_id)}`}>Open run</Link>}</>:"Not available"}</dd></div><div><dt>Snapshot generated</dt><dd>{utcDateTime(diagnostics.generated_at)}</dd></div></dl></>:<StatePanel title="Current database evidence pending" message="No present-state claim is made until diagnostics return."/>}</div></li>
        <li className={backup?"verified":"unavailable"}><span className="recovery-chain-marker">02</span><div><p className="eyebrow">Protected host evidence</p><h3>Latest finalized backup</h3>{recoveryError?<StatePanel kind="error" title="Backup evidence unavailable" message={recoveryError}/>:!backup?<StatePanel kind="unknown" title="No finalized backup evidence" message="No valid finalized bundle is indexed. Run the protected host backup command before relying on recovery."/>:<><div className="recovery-status-pair"><StatusBadge tone="success">Digest verified</StatusBadge><StatusBadge tone="success">Validation passed</StatusBadge></div><dl><div><dt>Backup ID</dt><dd><CopyControl value={backup.backup_id} label={`Copy backup ID ${backup.backup_id}`}/></dd></div><div><dt>Finalized</dt><dd>{utcDateTime(backup.finalized_at_utc)}</dd></div><div><dt>Exact size</dt><dd><code>{count(backup.size_bytes)} bytes</code></dd></div><div><dt>Schema / source</dt><dd><code>{backup.schema_version}</code> · <code>{backup.source_commit}</code></dd></div></dl></>}</div></li>
        <li className={restore?"verified":"unavailable"}><span className="recovery-chain-marker">03</span><div><p className="eyebrow">Isolated proof</p><h3>Latest restore drill</h3>{recoveryError?<StatePanel kind="error" title="Restore evidence unavailable" message={recoveryError}/>:!restore?<StatePanel kind="unknown" title="No isolated restore evidence" message="A backup alone does not prove restoreability. Run the isolated drill outside the browser."/>:<><div className="recovery-status-pair"><StatusBadge tone="success">Restore passed</StatusBadge><StatusBadge tone="success">Reconciliation {restore.reconciliation_status}</StatusBadge></div><dl><div><dt>Source backup</dt><dd><code>{restore.backup_id}</code></dd></div><div><dt>Drill completed</dt><dd>{utcDateTime(restore.completed_at_utc)}</dd></div><div><dt>Zero-mismatch proof</dt><dd>{restore.mismatch_count} mismatches · normal environment unchanged</dd></div><div><dt>Local drill duration</dt><dd><code>{restore.local_rto_seconds} seconds</code></dd></div></dl></>}</div></li>
      </ol>
    </section>}
    {canRead&&recovery&&<section className="surface recovery-retention" aria-labelledby="retention-heading"><div><p className="eyebrow">Bounded index</p><h2 id="retention-heading">Retention summary</h2><p>Only finalized bundles are counted. Pending or malformed bundles are not presented as backups.</p></div><dl><div><dt>Valid backups</dt><dd>{count(recovery.retention.valid_backup_count)}</dd></div><div><dt>Configured keep count</dt><dd>{count(recovery.retention.configured_keep_count)}</dd></div><div><dt>Ignored entries</dt><dd>{count(recovery.retention.ignored_entry_count)}</dd></div><div><dt>Index generated</dt><dd>{utcDateTime(recovery.generated_at_utc)}</dd></div></dl>{recovery.retention.ignored_entry_count!==0&&<StatePanel kind="unknown" title="Some recovery entries were excluded" message="Malformed, incomplete, or unsafe entries are not counted as valid evidence. Inspect host-side recovery tooling before relying on retention."/>}</section>}
    <section className="recovery-commands" aria-labelledby="recovery-commands-heading"><div className="section-heading"><div><p className="eyebrow">Copy only / Host controlled</p><h2 id="recovery-commands-heading">Safe host commands</h2><p>Run these reviewed repository commands from PowerShell in the LedgerSync workspace. This page cannot execute them.</p></div></div><div className="recovery-command-list">{commands.map((command)=><article key={command.value}><HardDrives aria-hidden="true"/><div><h3>{command.label}</h3><p>{command.detail}</p><CopyControl value={command.value} label={`Copy ${command.label} command`}/></div></article>)}</div></section>
    <section className="recovery-destructive-boundary" aria-labelledby="destructive-boundary-heading"><ShieldWarning weight="fill" aria-hidden="true"/><div><p className="eyebrow">Privilege boundary</p><h2 id="destructive-boundary-heading">Restore and reset are intentionally absent</h2><p>The browser cannot start a shell, choose a host path, replace the active database, delete volumes, or reset local state. Active restore/reset remains a deliberate host operation with separate review.</p></div></section>
  </>;
}
