"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

import type { Account, TransferDetail, TransferSummary } from "@/features/accounts/types";
import { CopyControl, PageHeader, Pagination, RecordLink, StatePanel, StatusBadge } from "@/features/console/components";
import { utcDateTime } from "@/features/console/format";
import { TransferForm } from "@/features/transfers/TransferForm";
import { formatMinorUnits } from "@/lib/money";

function financialTone(status: string) { return status === "posted" ? "success" as const : status === "rejected" ? "danger" as const : "warning" as const; }

export function TransferList({ transfers, nextCursor, busy, onMore }: Readonly<{ transfers: TransferSummary[]; nextCursor?: string; busy?: boolean; onMore: () => void }>) {
  if (!transfers.length) return <StatePanel title="No transfers found" message="No transfer records match this authorized scope and filter." />;
  return <section className="ledger-section"><div className="section-heading"><div><p className="eyebrow">Immutable history</p><h2>Transfer records</h2><p>Financial and downstream delivery outcomes remain separate.</p></div></div><div className="data-table-wrap" role="region" aria-label="Transfer comparison" tabIndex={0}><table className="data-table transfer-table"><thead><tr><th>Transfer</th><th>Route</th><th>Exact amount</th><th>Financial status</th><th>Delivery</th><th>Completed UTC</th><th>Action</th></tr></thead><tbody>{transfers.map((item)=><tr key={item.transfer_id}><td><CopyControl value={item.transfer_id}/></td><td><Link href={`/accounts/${item.source_account_id}`}>{item.source_account_id.slice(0,8)}…</Link><span aria-hidden="true"> → </span><Link href={`/accounts/${item.destination_account_id}`}>{item.destination_account_id.slice(0,8)}…</Link></td><td className="number-cell">{formatMinorUnits(item.currency,item.amount_minor)}</td><td><StatusBadge tone={financialTone(item.financial_status)}>{item.financial_status}</StatusBadge></td><td><StatusBadge tone={item.delivery_status==="retrying"||item.delivery_status==="dead"?"warning":"neutral"}>{item.delivery_status}</StatusBadge></td><td>{utcDateTime(item.completed_at)}</td><td><RecordLink href={`/transfers/${item.transfer_id}`} label="Open record"/></td></tr>)}</tbody></table></div><div className="record-card-list">{transfers.map((item)=><article className="record-card" key={item.transfer_id}><div><StatusBadge tone={financialTone(item.financial_status)}>{item.financial_status}</StatusBadge><StatusBadge tone={item.delivery_status==="retrying"||item.delivery_status==="dead"?"warning":"neutral"}>Delivery {item.delivery_status}</StatusBadge></div><strong>{formatMinorUnits(item.currency,item.amount_minor)}</strong><CopyControl value={item.transfer_id}/><small>{utcDateTime(item.completed_at)}</small><RecordLink href={`/transfers/${item.transfer_id}`} label="Open transfer"/></article>)}</div><Pagination nextCursor={nextCursor} busy={busy} onNext={onMore}/></section>;
}

export function TransfersView({ accounts, transfers, detail, error, loading, nextCursor, online, canWrite, writeUnavailableReason, tenantId, csrfToken, onRefresh, onMore }: Readonly<{ accounts: Account[]; transfers: TransferSummary[]; detail: TransferDetail | null; error: string | null; loading: boolean; nextCursor?: string; online: boolean; canWrite: boolean; writeUnavailableReason?: string; tenantId: string; csrfToken: string; onRefresh: () => Promise<void>; onMore: () => void }>) {
  const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const filtered=useMemo(()=>transfers.filter((item)=>(status==="all"||item.financial_status===status)&&`${item.transfer_id} ${item.source_account_id} ${item.destination_account_id}`.toLowerCase().includes(query.toLowerCase())),[transfers,query,status]);
  if (detail) return <><PageHeader eyebrow="Money movement / Immutable record" title="Transfer detail" description="The committed financial result is permanent; delivery evidence is shown separately."/><section className="identity-strip"><div><span>Transfer ID</span><CopyControl value={detail.transfer_id}/></div><div><span>Financial status</span><StatusBadge tone={financialTone(detail.financial_status)}>{detail.financial_status}</StatusBadge></div><div><span>Delivery status</span><StatusBadge tone={detail.delivery_status==="retrying"||detail.delivery_status==="dead"?"warning":"neutral"}>{detail.delivery_status}</StatusBadge></div><div><span>Completed</span><strong>{utcDateTime(detail.completed_at)}</strong></div></section>{(detail.delivery_status==="retrying"||detail.delivery_status==="dead")&&<StatePanel kind="unknown" title={`Money is posted; delivery is ${detail.delivery_status}`} message="The double-entry ledger is complete. Downstream delivery is tracked separately from financial posting."/>}<section className="surface detail-document"><p className="eyebrow">Exact transfer facts</p><strong className="detail-amount">{formatMinorUnits(detail.currency,detail.amount_minor)}</strong><dl className="evidence-list"><div><dt>Source account</dt><dd><Link href={`/accounts/${detail.source_account_id}`}>{detail.source_account_id}</Link></dd></div><div><dt>Destination account</dt><dd><Link href={`/accounts/${detail.destination_account_id}`}>{detail.destination_account_id}</Link></dd></div><div><dt>Journal transaction</dt><dd>{detail.journal_transaction_id?<CopyControl value={detail.journal_transaction_id}/>:"No journal created"}</dd></div><div><dt>Created</dt><dd>{utcDateTime(detail.created_at)}</dd></div></dl></section><section className="ledger-section"><div className="section-heading"><div><p className="eyebrow">Double-entry proof</p><h2>Ledger postings</h2></div></div>{detail.postings.length?detail.postings.map((posting)=><article className="posting-row" key={posting.posting_id}><StatusBadge tone={posting.direction==="credit"?"success":"neutral"}>{posting.direction}</StatusBadge><Link href={`/accounts/${posting.account_id}`}>{posting.account_id}</Link><strong>{formatMinorUnits(posting.currency,posting.amount_minor)}</strong><time>{utcDateTime(posting.occurred_at)}</time></article>):<StatePanel title="No postings" message="Rejected transfers do not create ledger postings."/>}</section><Link className="text-link back-link" href="/transfers">← Back to transfers</Link></>;
  return <><PageHeader eyebrow="Money movement / Internal only" title="Transfers" description="Prepare an exact transfer, then investigate its immutable result."/><div className="two-column-layout"><TransferForm accounts={accounts} tenantId={tenantId} csrfToken={csrfToken} disabled={!online||!canWrite} onPosted={onRefresh}/><aside className="guardrail-panel"><p className="eyebrow">Trust controls</p><h2>One intent, one movement</h2><ol><li>Only authorized active accounts are selectable.</li><li>Amounts use exact integer minor units.</li><li>Retries retain the same idempotency key.</li><li>Ledger, balance, audit, and outbox commit together.</li></ol>{!canWrite&&<p className="permission-note">{writeUnavailableReason ?? "Read-only role: transfer posting is not permitted."}</p>}</aside></div><div className="filter-bar transfer-filters"><label>Search transfers<input type="search" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Transfer or account ID"/></label><label>Financial status<select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="all">All statuses</option><option value="posted">Posted</option><option value="rejected">Rejected</option></select></label><button className="button secondary" type="button" disabled={!online||loading} onClick={()=>void onRefresh()}>Refresh history</button></div>{error?<StatePanel kind="error" title="Transfer history unavailable" message={error}/>:<TransferList transfers={filtered} nextCursor={nextCursor} busy={loading} onMore={onMore}/>}</>;
}
